# -*- coding: utf-8 -*-
"""TradutorDeArtigos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122Km8w8z11lg6VkD7ZN9T_ohuRMCY7fB
"""

!pip install requests beautifulsoup4 openai langchain-openai

import requests
from bs4 import BeautifulSoup

def extract_text_from_url(url):
    response = requests.get(url)

    if response.status_code == 200:
      soup = BeautifulSoup(response.text, 'html.parser')
      for script_or_style in soup(['script', 'style']):
        script_or_style.decompose()
      texto = soup.get_text(separator=' ')
      #limpar texto
      linhas = (line.strip() for line in texto.splitlines())
      parts = (phrase.strip() for line in linhas for phrase in line.split("  "))
      texto_limpo = '\n'.join(part for part in parts if part)
      return texto_limpo
    else:
        print(f"Failed to fetch the URL. Status code: {response.status_code}")
        return None

    text = soup.get_text()
    return text

    extract_text_from_url('https://dev.to/theplebdev/java-data-creating-an-entity-with-jpa-and-hibernate-56jf')

from langchain_openai.chat_models.azure import AzureChatOpenAI

client = AzureChatOpenAI(
    azure_endpoint= "https://dio-oai-bootcamp-eastus-001.openai.azure.com/",
    api_key= "9I826NqEHKKLEynP9hSZ7MtSamQ4DC5QOnRKfvgUjyQdDhe7TSWxJQQJ99AKACHYHv6XJ3w3AAABACOGxUcP",
    api_version= "2024-02-15-preview",
    deployment_name= "gpt-4o-mini",
    max_retries=0
)

def translate_article(text, lang):
  messages = [
      ("system" , "Voc^e atua como tradutor de textos"),
      ("user", f"Traduza o {text} para o idioma {lang} e responda em markdown")
  ]

  response = client.invoke(messages)
  print(response.content)
  return response.content

  translate_article("This series is going to be all things Java and data related. I just want to do some big things with big data in Java", "português")

url = 'https://dev.to/theplebdev/java-data-creating-an-entity-with-jpa-and-hibernate-56jf'
text = extract_text_from_url(url)
article = translate_article(text, "pt-br")

print(article)